# Generated by Django 5.2.1 on 2025-05-16 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_brand_alter_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="base.menu",
            ),
        ),
    ]
